test_format = 1.0

[default]

	# ------------
    # Tests to run
    # ------------

	exclude = ["change_url"]

	# -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.5f452d7acda69f4897ce1344678d0f59ccb162ca.name = "Upgrade from 5.0.0~ynh2"
