test_format = 1.0

[default]

	# ------------
    # Tests to run
    # ------------

	exclude = ["change_url"]

	# -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.00a1a6e7.name = "Upgrade from 5.4"
