#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

#storage_quota="20gb"
#ynh_app_setting_set --key=storage_quota --value=$storage_quota

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir" --source_id="xftp"

mkdir -p /etc/opt/simplex-xftp /etc/opt/simplex /var/opt/simplex-xftp /var/opt/simplex
chown -R $app:$app  /etc/opt/simplex-xftp /etc/opt/simplex /var/opt/simplex-xftp /var/opt/simplex

chmod +x $install_dir/smp-server
chmod +x $install_dir/xftp-server

#=================================================
# SPECIFIC SETUP
#=================================================

public_ip4="$(curl -s ip.yunohost.org)" || true
ynh_app_setting_set --key=public_ip4 --value=$public_ip4

pushd "$install_dir"
	./smp-server init --no-password --ip $public_ip4 --store-log --yes
	./xftp-server init --ip $public_ip4 --quota '20gb' --store-log --path $data_dir
popd

fingerprint=$(cat /etc/opt/simplex/fingerprint)
ynh_app_setting_set --key=fingerprint --value=$fingerprint

xftp_fingerprint=$(cat /etc/opt/simplex-xftp/fingerprint)
ynh_app_setting_set --key=xftp_fingerprint --value=$xftp_fingerprint

ynh_replace --match="port: 443" --replace="port: $port_xftp" --file="/etc/opt/simplex-xftp/file-server.ini"

chown -R $app:$app "/etc/opt/simplex"
chown -R $app:$app "/etc/opt/simplex-xftp"

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration..."

#ynh_config_add --template="file-server.ini" --destination="/etc/opt/simplex-xftp/file-server.ini"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd
ynh_config_add_systemd --service=xftp --template=../conf/xftp.systemd.service

yunohost service add $app --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"
yunohost service add xftp --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port_xftp"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"
ynh_systemctl --service="xftp" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
