#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"
chmod +x $install_dir/smp-server

#=================================================
# SPECIFIC SETUP
#=================================================

pushd "$install_dir"
	public_ip4="$(curl -s ip.yunohost.org)" || true
	ynh_app_setting_set --app=$app --key=public_ip4 --value=$public_ip4
	./smp-server init --no-password --ip $public_ip4 -y
popd

fingerprint=$(cat /etc/opt/simplex/fingerprint)
ynh_app_setting_set --app=$app --key=fingerprint --value=$fingerprint

chown -R $app:$app "/etc/opt/simplex"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=6

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
