#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove $app
	yunohost service remove xftp
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config
ynh_remove_systemd_config --service=xftp

# Remove the app directory securely
ynh_secure_remove --file="/etc/opt/simplex"
ynh_secure_remove --file="/etc/opt/simplex-xftp"
ynh_secure_remove --file="/var/opt/simplex"
ynh_secure_remove --file="/var/opt/simplex-xftp"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
