#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"
ynh_systemctl --service=xftp --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

xftp_fingerprint=$(cat /etc/opt/simplex-xftp/fingerprint)
ynh_app_setting_set --key=xftp_fingerprint --value=$xftp_fingerprint

if [ -z "$domain" ]; then
	ynh_die "You need to define a domain for Simplex before upgrading. `yunohost app setting simplex domain -v <smp.domain.tld>`"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="/usr/local/bin/$app"
ynh_setup_source --dest_dir="/usr/local/bin/$app" --source_id="xftp"

chmod +x "/usr/local/bin/$app/smp-server" "/usr/local/bin/$app/xftp-server"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="smp-server.ini" --destination="/etc/opt/simplex/smp-server.ini"
ynh_config_add --template="file-server.ini" --destination="/etc/opt/simplex-xftp/file-server.ini"

chown $app:$app "/etc/opt/simplex/smp-server.ini" "/etc/opt/simplex-xftp/file-server.ini"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service=xftp --template=../conf/xftp-systemd.service

yunohost service add $app --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"
yunohost service add xftp --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port_xftp"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"
ynh_systemctl --service=xftp --action="start" --log_path="systemd"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
